// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 👇 import your provider
import { BirthdayProvider } from "@/app/context/BirthdayContext";
import { ClerkProvider } from '@clerk/nextjs'; // adjust path if needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    {/* 👇 wrap entire app in provider */}
    <ClerkProvider>
      <BirthdayProvider>
        {children}
      </BirthdayProvider>
    </ClerkProvider>
    </body>
    </html>
  );
}
